language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
notifications:
  slack:
    secure: DHsua3z2KqAsBAVzQ3opk1CPMNPjFRXS+sfZ6IyqAUjT+OVngJudUQTm+JQ33wGpeTjyyYOtcOWm9GjcWn/2RklwbDD/tb9fd2ENolleXjNRRsJb+EV0E7l0xf1ZOB+hi5R1qJ7S4Lt/1C32CfnXag7TMSETTVUxovfhYIXsYb0mdlq/ySrvtiM1Fw5IfL9SQQblJHuEe/Op0Q1StQNkQGZjhrmeZVEG9Pv3raZMGIcxI9in6FiNmn4s+uQ2y5M83a2lkH0ZO0A4LrjWjA7eHwfnBwJ3YBWJXqJb7btyrL+9De114yxIaffEBXSuSD/3AT/FSU5zN2ptQSrGIlY4i4Cx4GSGbY+SmO6qJ7Gu1KNMxGESoCCcaGRZa86PxtvXb9as7I90HCCmr3yPaUYZgXXdn5SaS7V0uP47v/+TYyQ69uM7eDS4JrUbf+aZzz8e7AzjObb1OGdN1FI6h5lMEm/4rPjLPIBI3THqEzBfuGj29mfnogss78KfY9BIpzZWF4NveUR6zxhuH76rs66EzTzJJ6FhxCyyfL52fE5vphpNDgeF5OlVnaq0KT2pK9xAygOfrVhFOY2T65eKRtpnzH36wCNH3GaIz1T4tkWACvWx4tudO/aM5+fHHopFEsk+hchdWBVy0px7oWDD77z++5swuv/5NCL9WAJbswrTtTg=
env:
  global:
  - secure: MLrsHHij0fpyfS72fmd30y/gmpxxieNRvv5UCyeu8bcKzXmvqTZY0trTDK0EphdfjQaGbtlW3o4HIuIIzPaM7cgCvZzoGi16QOhQ2n7wekq153f4jIO+fEODoUf5hlrkQug9SJvk9gfFqN1Hqjxk9kCCzwdirZv2Ox8OqWIesunGPjSg1879aSiVcLjwTlcvzgRst1hoDiv06Sv+D9dylFTwZPOH4t7He85TR3pL1swXyrZeOnggKkeOUmo3Z2vFq8dS1bZkWDQPWtTeCKNd8Pnd4/K4bH0N3IGaFIEMU4lv8h286mjNLXMdAOG7OqvDIDOESBmCwd9N/TKHw3SCOnk+ZQA67BjgAOI8ncte/aWt1Np1Yg6RrwmvcGWvn75sdsp6gOA7UxOtePiBmD85u8UBeA4RqQdI9knli0k9imd89wsR90Ro8QueLVbsfm7IAHKunV5GyAjOn63TPF0La3Kk/94RdCUIlQ4qFbiVjqy1JCUupXYBGsvLN6oRM1nFv5Qls017QlFDQqZZ4c7L3Uist+/yhaOD7w91Lut3V9WqnAL1Wxm0anjzk7UXLWQ+0tI2Y0xRHoEiRJu/C5Ay7mk8XNtrB8DPYoeb+hV/oU4OPKmSwd2/cBkDl37rqk9h/O+9tCKSYqzCvy+YU6pVFLLkFeOiAoDqNbEUee738Nw=
  - secure: o57UAYHbmACpmR+7HRj1ZPcKR0gv9PPQoYX3g67XL/tS590HSncQtivzoZ9mE4cP4PMn4U24H1GWt9Vt8Wf8WUNL2aMp1RYP47RJ5qBnmh+kMDOFIR2XHQ3W+US64HuFAE173k/t7zBBk3fSf2qhGlM1Kvt2qtgrQ8OPmBpDhAjOjdluEbbxQJbWYCgPcfHbLhI0axSfnuMh7tZdKtjNBBGM8TLAtSxSlknMcGbARUh7Tr2mWgm50yi7SI626JHTx60dxc8vxV9Zu+AK40RlSPnTPUk1vqAwL9gh7AgACtlxLQ3slc5qbNGzfypTBMAPrcZm5hc8kfn69kUFi33sV++lpFHzJZDu7w0RZTM0ZDWD8LfjBpifxxzmaB4fes8UizNswh3uNbTtvOhXk4LC5hpF4eLj3BHNJTAXV5GbywHToSrJORsND9cqEjr13HDNxpFnSuaXPWy+93qhoAhwpxDalHWux5YhLgAZoXvrtdml26XFLOJWHPLyYIpNnwVs2NWbPhpD/c0spddEMwTA5Ez5zoC3f/a/W6yOTJ1rMfV6z8he02W0LXaIQbGrQhLlP1ivoJZQG1pQjXXxKgCo69RfZSy1azg/9/U9PWCrwLCz4sS8zbBz4buXzJ5Kor76JqCXXdrePy+N2dzEzOhqO8EiB1OEsUvQRLCjnezguo0=
before_deploy:
  - echo "$APP_ID_OR_NAME"
deploy:
  provider: script
  script: scripts/restart_hubot
  all_branches: true
