language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
notifications:
  slack:
    secure: DHsua3z2KqAsBAVzQ3opk1CPMNPjFRXS+sfZ6IyqAUjT+OVngJudUQTm+JQ33wGpeTjyyYOtcOWm9GjcWn/2RklwbDD/tb9fd2ENolleXjNRRsJb+EV0E7l0xf1ZOB+hi5R1qJ7S4Lt/1C32CfnXag7TMSETTVUxovfhYIXsYb0mdlq/ySrvtiM1Fw5IfL9SQQblJHuEe/Op0Q1StQNkQGZjhrmeZVEG9Pv3raZMGIcxI9in6FiNmn4s+uQ2y5M83a2lkH0ZO0A4LrjWjA7eHwfnBwJ3YBWJXqJb7btyrL+9De114yxIaffEBXSuSD/3AT/FSU5zN2ptQSrGIlY4i4Cx4GSGbY+SmO6qJ7Gu1KNMxGESoCCcaGRZa86PxtvXb9as7I90HCCmr3yPaUYZgXXdn5SaS7V0uP47v/+TYyQ69uM7eDS4JrUbf+aZzz8e7AzjObb1OGdN1FI6h5lMEm/4rPjLPIBI3THqEzBfuGj29mfnogss78KfY9BIpzZWF4NveUR6zxhuH76rs66EzTzJJ6FhxCyyfL52fE5vphpNDgeF5OlVnaq0KT2pK9xAygOfrVhFOY2T65eKRtpnzH36wCNH3GaIz1T4tkWACvWx4tudO/aM5+fHHopFEsk+hchdWBVy0px7oWDD77z++5swuv/5NCL9WAJbswrTtTg=
